services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tokosa-server
    env_file:
      - ./server/.env
    ports:
      - '3000:3000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tokosa-client
    ports:
      - '80:80'
